// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfY0dQJQYEvFM8RkEqYA5HOMKm91VB3M',
    appId: '1:528829822102:web:fb1a5824caaab1981e3eb7',
    messagingSenderId: '528829822102',
    projectId: 'my-flutter-base-7e27e',
    authDomain: 'my-flutter-base-7e27e.firebaseapp.com',
    storageBucket: 'my-flutter-base-7e27e.firebasestorage.app',
    measurementId: 'G-QMERXTBQQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuVvT-cAclmSKaXZ58hg2mLmmItgtcR7s',
    appId: '1:528829822102:android:39e9c350a7fd31b41e3eb7',
    messagingSenderId: '528829822102',
    projectId: 'my-flutter-base-7e27e',
    storageBucket: 'my-flutter-base-7e27e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsvGq-QOoX3cGunvUrkXxHlkWqRj2mFSk',
    appId: '1:528829822102:ios:1bf87fee4f61eb491e3eb7',
    messagingSenderId: '528829822102',
    projectId: 'my-flutter-base-7e27e',
    storageBucket: 'my-flutter-base-7e27e.firebasestorage.app',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsvGq-QOoX3cGunvUrkXxHlkWqRj2mFSk',
    appId: '1:528829822102:ios:1bf87fee4f61eb491e3eb7',
    messagingSenderId: '528829822102',
    projectId: 'my-flutter-base-7e27e',
    storageBucket: 'my-flutter-base-7e27e.firebasestorage.app',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwfY0dQJQYEvFM8RkEqYA5HOMKm91VB3M',
    appId: '1:528829822102:web:11e83c562727bc551e3eb7',
    messagingSenderId: '528829822102',
    projectId: 'my-flutter-base-7e27e',
    authDomain: 'my-flutter-base-7e27e.firebaseapp.com',
    storageBucket: 'my-flutter-base-7e27e.firebasestorage.app',
    measurementId: 'G-NTD73PLPH7',
  );
}
